#!/bin/sh /etc/rc.common

USE_PROCD=1          # 使用 procd 管理进程
START=50             # 启动顺序
STOP=50              # 停止顺序

# 服务名称
# PROG=/usr/sbin/myubus

start_service() {                               # 定义服务启动函数（执行 /etc/init.d/xxx start 时会调用）
    
    logger -t myapp "start_service start"

    procd_open_instance                         # 打开一个 procd 实例，开始配置要启动的进程
    procd_set_param command /usr/sbin/myubus    # 指定要启动的程序及其路径（实际执行的命令）
    procd_set_param respawn                     # 启用崩溃自动重启机制（进程异常退出会自动重新拉起）
    procd_set_param stdout 1                    # 将程序的标准输出重定向到系统日志（可用 logread 查看）
    procd_set_param stderr 1                    # 将程序的错误输出重定向到系统日志
    procd_set_param file /etc/config/myapp      # 监听该配置文件变化（文件变动时会触发服务重载）
    procd_close_instance                        # 结束实例配置并通知 procd 启动该进程

    logger -t myapp "start_service end"
} 


# =========================
# 重新加载配置
# =========================
reload_service() {
    logger -t myapp "reload_service() called"
    # 如果程序支持 reload 信号，可以：
    procd_send_signal myapp
}

# =========================
# 停止服务
# =========================
stop_service() {
    logger -t myapp "stop_service() called"
}

service_triggers() { # 定义触发器
    logger -t myapp "service_triggers() registered"
    procd_add_reload_trigger myapp
}